# Generated by Django 4.0.4 on 2022-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
