# Generated by Django 4.0.4 on 2022-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_price_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
